### ISSUE TITLE
Support sql-server database import

### ISSUE THREAD

**Issue by ashrafsabrym** [azimuttapp/azimutt#113]

**Comment by loicknuchel** [comment]
Hi @ashrafsabrym thanks for the request.
Will work on it probably in september and will keep you informed here :)

In the meantime, you can export your database schema and import it as SQL file in Azimutt ;)

Have a great day,
Loïc

**Comment by loicknuchel** [comment]
Working on it on https://github.com/azimuttapp/azimutt/pull/227

**Comment by loicknuchel** [comment]
Hi @ashrafsabrym 
I'm quite happy to finally release SQL Server support in Azimutt 🤩
Give it a try and tell us how it went ;)
Cheers!

**Comment by ashrafsabrym** [comment]
Thank you very much
