### ISSUE TITLE
Support mysql database import

### ISSUE THREAD

**Issue by DpkTewatia** [azimuttapp/azimutt#114]

**Comment by loicknuchel** [comment]
Hi @DpkTewatia thanks for the request.
Will work on it probably in september and will keep you informed here :)

In the meantime, you can export your database schema and import it as SQL file in Azimutt ;)

Have a great day,
Loïc

**Comment by cmccoy98** [comment]
Any update on this feature?

**Comment by loicknuchel** [comment]
Hi @cmccoy98 
We clearly have it in mind but have a lot to do (like Docker installation and others).
The biggest parts is looking into MySQL internals to know which query to use to extract the needed data (like in https://github.com/azimuttapp/azimutt/blob/main/backend/lib/azimutt/analyzer/postgres.ex).
If you can build such queries, it would be easier for us to move forward quickly on this.

**Comment by loicknuchel** [comment]
Working on it: https://github.com/azimuttapp/azimutt/pull/225

**Comment by loicknuchel** [comment]
Done 🎉
