### ISSUE TITLE
Export in SQL (DDL)

### ISSUE THREAD

**Issue by ahoy-jon** [azimuttapp/azimutt#117]
With a view, would it be possible to export it in SQL?

**Comment by loicknuchel** [comment]
Hey!
What do you want to export in SQL precisely?
Just one view (or table)? The content of a layout? (only visible columns?) Everything present in the project?
Could you describe a bit more your use case?

This is not planned for now but should not be too hard (just a bit long for every db system ^^).
In the meantime, as you can access your project content in the JS console, you can do it "by hand":
```js
azimutt.getVisibleTables().map(t => {
  return `CREATE TABLE ${t.table} (
${t.columns.map(c => `  ${c.name} ${c.type}`).join(',\n')}
);`
}).join('\n\n')
```
(you can explore `azimutt` and `azimutt.project` objects for more specific needs)

**Comment by loicknuchel** [comment]
Hi @ahoy-jon 
Just added it (Postgres & MySQL), you can now export the whole project or just a layout.
