### ISSUE TITLE
Left panel problem

### ISSUE THREAD

**Issue by ahoy-jon** [azimuttapp/azimutt#118]
![image](https://user-images.githubusercontent.com/83247/188137839-f839ff0d-f76f-4fff-aaac-17ad8c8c49b5.png)

I have this issue in the latest chrome, and the WebKit of a desktop app (notion.so)
There is nothing in the logs.

**Comment by loicknuchel** [comment]
Ooups... Thanks for reporting :+1:

**Comment by loicknuchel** [comment]
Fixed!
