### ISSUE TITLE
Schema doesn't show on Firefox

### ISSUE THREAD

**Issue by gdotdesign** [azimuttapp/azimutt#12]
I was just wanted to let you know that there is a runtime error when trying in Firefox:

![image](https://user-images.githubusercontent.com/302692/132175360-dd09f57f-846d-479a-a7dd-3010d1da31ef.png)

**Comment by loicknuchel** [comment]
Hi @gdotdesign 
Thanks a lot for the report, indeed it's a big problem!
But thanks to you, now it's fixed :tada:
