### ISSUE TITLE
AML editing pane too hidden

### ISSUE THREAD

**Issue by michi-zuri** [azimuttapp/azimutt#127]
Hi Loïc

It took me until now literally several hours since September to find this Update Schema button, even though I was trying really hard to find a way to edit custom sources without editing the downloaded json project file:

![grafik](https://user-images.githubusercontent.com/26734536/197418034-555a60ad-72b6-4460-beb2-7c5301b99fb1.png)

since I was expecting this functionality here in the Settings pane:

![grafik](https://user-images.githubusercontent.com/26734536/197418069-2beb196a-aa78-421f-b2bb-ac79399957d5.png)

Now that I have found it, I am still missing the option to add an AML source from the Settings pane:
![grafik](https://user-images.githubusercontent.com/26734536/197418195-28a9226d-4dd3-4c0c-98db-e63e9e49a96e.png)

and I'd suggest also adding the Update schema pane toggle to the advanced feature drawer:
![grafik](https://user-images.githubusercontent.com/26734536/197418258-774d0eff-e416-426e-b420-2384df8b5dd4.png)

All the best
Michi

**Comment by michi-zuri** [comment]
Great, I'm really looking forward to prototyping data models now with AML ! Thanks so much for sharing this with the world!

**Comment by loicknuchel** [comment]
Awesome!
I hope you will like it as much as I do ;)

**Comment by loicknuchel** [comment]
Hi @michi-zuri 
Deployed the fix, closing the issue.
Don't hesitate to check and re-open if you still see improvements.
Cheers!
