### ISSUE TITLE
Popup window navigation buttons showing errors are not functional

### ISSUE THREAD

**Issue by PhBastiani** [azimuttapp/azimutt#13]
Popup window navigation buttons showing errors are not functional

Tested with Firefox

**Comment by loicknuchel** [comment]
Thanks for the issue, will check that.

**Comment by loicknuchel** [comment]
After a little investigation, this is the good time for me to improve the import process reporting (will fix also #14 issue if I understand well).
But this will take some time (ie: not tonight ^^).
In the meantime, I fixed #15 so you could be able to play a bit with Azimutt :smile: 
I hope you will enjoy!
And again, thanks for the reports :+1:

**Comment by loicknuchel** [comment]
I'm closing this issue as it will be addressed in https://github.com/azimuttapp/azimutt/issues/17.
Feel free to reopen if it's different.
