### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by kartikeyporwal** [azimuttapp/azimutt#139]
Hi, Thanks for developing this project.

I tried to build and run this but I encountered so many errors because the stack looks unique. Please consider providing the docker support to test `azimutt`. I am sure there would many users who find such difficulty and would love to test using Docker.

**Comment by loicknuchel** [comment]
Hi @kartikeyporwal 

Indeed, setting up everything can be quite challenging.
We reached a point we can now focus a bit more about distribution and clearly Docker is in our list.
Not sure when we could set it up but most probably before the end of the year.

Thanks for your interest, don't hesitate to send other feedback or cheers ;)

**Comment by faab007nl** [comment]
Is there a update on the progress of the creation of a docker file / docker-compose?

**Comment by sbouaked** [comment]
Hello @faab007nl  ! We are still working on, you can try our current version on this branch https://github.com/azimuttapp/azimutt/tree/feat/dockerize-app. I will try to finish it this week !

**Comment by sbouaked** [comment]
You can try our first image here ! https://github.com/azimuttapp/azimutt/pkgs/container/azimutt

**Comment by faab007nl** [comment]
I tried it using the base docker-compose from the dockerize-app branch.
Changed the build to image: ghcr.io/azimuttapp/azimutt:feat-dockerize-app

The backend does not wan't to start.
Here are the logs.
https://pastebin.com/feittkuy

**Comment by sbouaked** [comment]
You need to create your `.env` file with this variables : 
```
### Define your own GitHub App for authentification
export GITHUB_CLIENT_SECRET=
export GITHUB_CLIENT_ID=

### Stripe and Malign API is not mandatory
export STRIPE_API_KEY=
export STRIPE_WEBHOOK_SIGNING_SECRET=
export MAILGUN_API_KEY=
export MAILGUN_DOMAIN=
export MAILGUN_BASE_URL=


### Define your S3 informations with this. We use clever cloud, so the variables name are a little bit specific for now
export CELLAR_ADDON_KEY_ID=
export CELLAR_ADDON_HOST=
export CELLAR_ADDON_KEY_SECRET=
export CELLAR_BUCKET=

### Phoenix variables
export SECRET_KEY_BASE=XXX
export GUARDIAN_SECRET_KEY=XXX
export PHX_HOST=localhost
export PORT=4000
export PHX_SERVER=true
export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/azimutt_dev
