### ISSUE TITLE
Add self-hosted support

### ISSUE THREAD

**Issue by cmccoy98** [azimuttapp/azimutt#140]
Hello,

Currently would like to have access to hosting the repository locally when not connected to the internet. Are there plans in the future for the project to support this?

**Comment by loicknuchel** [comment]
Hi @cmccoy98 

Not sure what you want exactly.
If you are looking for a self-hosted solution, we plan to propose a Docker installation: https://github.com/azimuttapp/azimutt/issues/139
Is it  what you are looking for?

**Comment by agupta-jobie** [comment]
Hi, we are trying to self-hosting  Azimutt as an internal tool, we want to setup the highest tier by default for the organization for that I tried setting up
```
ORGANIZATION_DEFAULT_PLAN=pro 
```
but it didn't work out as I am trying to add a member to the org it is saying that hey Billing not available.
