### ISSUE TITLE
Fit diagram to screen flaky

### ISSUE THREAD

**Issue by stacy-rendall** [azimuttapp/azimutt#142]
The "Fit diagram to screen" button doesn't seem to work very well. The issue can be reproduced with an example project:

1. New project
2. Export Sample > Gospeak.io (26 tables) > Load sample
3. Use "-" button to zoom out to (for example) ~25%
4. Hit "Fit diagram to screen" button 

Result: diagram disappears, and it can be hard to find
Expected result: Azimutt pans/zooms so that diagram fits to screen

**Comment by loicknuchel** [comment]
Thanks for the report.
I noticed some cases where it's not working as expected.
Already tried to debug but without much success so far.
I will give it an other try but not too long as, as frustrating as it can be, it's not really deal breaker (even if doesn't reflect the level I want Azimutt to be).

**Comment by loicknuchel** [comment]
Fixed it working on auto-layout :tada: 
That's my personal christmas gift :wink:

**Comment by stacy-rendall** [comment]
Seems to be working great on all the ERDs I have :) Nice work!
