### ISSUE TITLE
This basic DDL cannot be parsed

### ISSUE THREAD

**Issue by PhBastiani** [azimuttapp/azimutt#15]
[ddl.zip](https://github.com/azimuttapp/azimutt/files/7116772/ddl.zip)

**Comment by loicknuchel** [comment]
Hi @PhBastiani 

Thanks a lot for the report, it was due to forgetting `\r` ^^
It's fixed now :smile:

**Comment by PhBastiani** [comment]
Fixed with side effect on the display
<img width="190" alt="BugTable" src="https://user-images.githubusercontent.com/900472/132305189-3a741184-d91f-4400-a34d-7a486af179cf.png">

**Comment by loicknuchel** [comment]
Hi @PhBastiani 

You had no luck of trying it just during the rollout of a bug ^^
It's fixed now.
Can you check this and close the issue if it's fine ?

Thanks!

**Comment by PhBastiani** [comment]
Great success :)
