### ISSUE TITLE
Parse Add CONSTRAINT syntax (enhancement)

### ISSUE THREAD

**Issue by michelc** [azimuttapp/azimutt#16]
My schema for a SQL Server database contains `ADD CONSTRAINT` for primary and foreign keys. When I try to import this schema, I get several error messages:

* Can't parse add constraint: 'ADD CONSTRAINT [PK_dbo.Travels] PRIMARY KEY ([Travel_ID])'
* Can't parse add constraint: 'ADD CONSTRAINT [FK_dbo.Travels_dbo.Booklets_Booklet_ID] FOREIGN KEY ([Booklet_ID]) REFERENCES ...
* Statement not handled: '/* ---------- Travels */ CREATE TABLE [Travels] ( [Travel_ID] int ...

A subset from my schema if you want to test:
```
/* ---------- Booklet
*/

CREATE TABLE [Booklets] (
  [Booklet_ID] int identity(1,1) not null
, [Title] nvarchar(100) not null
, [Year] nvarchar(20) not null
, [Notes] ntext
, [IsReadOnly] bit not null
);

ALTER TABLE [Booklets] 
    ADD CONSTRAINT [PK_dbo.Booklets] PRIMARY KEY ([Booklet_ID]);


/* ---------- Travels
*/

CREATE TABLE [Travels] (
  [Travel_ID] int identity(1,1) not null
, [Booklet_ID] int not null
, [Position] int not null
, [Title] nvarchar(100) not null
, [Subtitle] nvarchar(100)
, [TravelType] int not null
, [Notes] ntext
);

ALTER TABLE [Travels] 
    ADD CONSTRAINT [PK_dbo.Travels] PRIMARY KEY ([Travel_ID]);

ALTER TABLE [Travels] 
    ADD CONSTRAINT [FK_dbo.Travels_dbo.Booklets_Booklet_ID] FOREIGN KEY ([Booklet_ID]) REFERENCES [Booklets]([Booklet_ID])
    ON UPDATE NO ACTION ON DELETE CASCADE;
```

**Comment by loicknuchel** [comment]
Hi @michelc 

Thanks for the report!

Indeed, I was not expecting the `[]` in the table and column names, so that's probably why it failed.
Thanks for the example, I will improve the parser to make this work.

In the meantime, if you remove the brackets and also the comments (I handle only `--` for now) you should be able to use Azimutt.

I will notify you when everything works well for you!

**Comment by michelc** [comment]
Thank you. The `[]` may be from the tool I'm using, but I think it's something very common with SQL Server.

**Comment by loicknuchel** [comment]
Interesting.
Do you think I should keep them in the name or just remove them to make the name clearer ?
What your other tools do ?

**Comment by michelc** [comment]
You should remove them from the name. It's like `` around names in MySQL.

**Comment by loicknuchel** [comment]
Hi @michelc 

I just deployed a new version of the SQL parser and it handle well the example you provided (thanks again for it, it was really helpful), **except the multi-line comments** (sorry, you will have to remove them manually, I still don't know how to manage them properly).

Can you check this out and close the issue if this is fine ?

Thanks!

**Comment by michelc** [comment]
Merci !
