### ISSUE TITLE
Close all button for notifications

### ISSUE THREAD

**Issue by opsb** [azimuttapp/azimutt#17]
Parsing my postgres schema generated a large number of errors. None of them were important so I was happy to ignore them all but I was left with a large number of notifications to close. A close all button would be really handy.

(happy to open a PR if we agree the design)

**Comment by opsb** [comment]
Regarding UX, maybe it could be cmd-click? I see there aren't any key combos in the project yet. https://package.elm-lang.org/packages/ohanhi/keyboard/latest/Keyboard could be an option.

**Comment by loicknuchel** [comment]
Hi, in fact there is a close button but it's on the right, quite small and sometimes not really visible :disappointed: 
So yes, could be largely improved :D

An cmd-click option could be fine also (but not sure how to tell it to users ^^).

Will be happy to review a PR from you :+1:

**Comment by hansvb** [comment]
Slightly related (small nuisance so maybe not worth a separate issue): when I scroll using touchpad over the (red) errors, when my mousepointer is on the background-area (gray) it scrolls the background-area instead. It would be better if all the errors were in one (transparent) container-widget? 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/8103741/135464736-14d7e65a-c902-4113-b38c-17ed5be9477f.png">

**Comment by loicknuchel** [comment]
Hi @hansvb 

Thanks for your comment.
It's clearly a not ideal UI and I'm currently looking into improving it.

My current take is to move away from this "quick and dirty" UI and open a report modal at the end of the import with some logs inside, so it's clearer for you to see what happened.

What do you think about this?

**Comment by loicknuchel** [comment]
Hi everyone,

I'm working on a new UI that will improve this and just wanted your feedback on my current (new) design:

![screencapture-localhost-8000-projects-new-2021-12-02-07_54_24](https://user-images.githubusercontent.com/653009/144372933-c4ec6663-14a9-45ec-ac03-2d6974b1063c.png)

What do you think?

**Comment by loicknuchel** [comment]
Hi @opsb and @hansvb 
I finally finished and deployed my UI revamp. I drastically changed the project creation and it should be much better now so I will close this issue.
Feel free to open again or other if you see some possible improvements.
Cheers!
