### ISSUE TITLE
why I can't share my private link?

### ISSUE THREAD

**Issue by paulzhong048** [azimuttapp/azimutt#178]
why I can't share my private link as below?

https://azimutt.app/d6c332cd-4b0e-48ea-b3ef-cd8a4d9b6699/9753e718-abd1-40b9-8a8d-099eb2ef2611?layout=initial%20layout&token=92d007f5-ed15-401c-b8dd-d7769ca5c200

**Comment by loicknuchel** [comment]
Hi @paulzhong048 
Small bug on our side, thanks for reporting it.
It's fixed now 😉
Can you confirm and close the issue if it's fine?
