### ISSUE TITLE
Unable to move tables

### ISSUE THREAD

**Issue by ComeBertrand** [azimuttapp/azimutt#18]
I managed to import my schema with no issue, but I can't move some tables that I display which makes it hard to create a layout (especially when they appear on top of each other).

There are no errors appearing in the console as far as I can tell.

**Comment by loicknuchel** [comment]
Hi @ComeBertrand 

Thanks for opening this issue.
Can I ask which browser do you use and what did you do to move a table ?

It work better on desktop, with drag (mouse down, then move, then mouse up)

**Comment by ad-si** [comment]
When loading the base example I can't move the role_user table.

**Comment by loicknuchel** [comment]
Hi @ad-si 
Thanks for your comment.
Indeed, I had a bug which prevented tables with an `_` to be moved ^^
It's fixed now :)

@ComeBertrand, can you check if this fix your problem ? (do you still have some trouble moving tables?)
If it's fine, can you close the issue ? 🙏

**Comment by ComeBertrand** [comment]
@loicknuchel Yes, it's working fine now! Thx
