### ISSUE TITLE
Visual Query Builder

### ISSUE THREAD

**Issue by zxdywy** [azimuttapp/azimutt#183]
I hope to add the function of Visual Query Builder
![显示自定义SQL](https://user-images.githubusercontent.com/128122096/226599278-6b46fe22-520a-459e-aeb3-7c66fcf45ff4.gif)

**Comment by loicknuchel** [comment]
Hi @zxdywy 
Thank you for the suggestion.
Azimutt is firstly built to explore the database schema (navigating between tables) and we plan to expand it a lot towards database exploration and analysis.
I'm not sure query building is a huge issue and would make a huge difference for our users (but maybe I miss something).
What we are planning is to use GPT-4 to generate queries from english description, based on the database schema, but not really sure about this kind of visual query builder.
What do you think? Do I miss something important?
Cheers!

**Comment by loicknuchel** [comment]
Closing the issue as not planned and inactive.
Thanks for your contribution, don't hesitate to submit other ideas ;)
