### ISSUE TITLE
Broken roadmap link in the README 🔗->💥 

### ISSUE THREAD

**Issue by nicokosi** [azimuttapp/azimutt#206]
Hello, 👋 

The [roadmap link](https://github.com/azimuttapp/azimutt/projects/1) in the [README](https://github.com/azimuttapp/azimutt#readme) returns HTTP 404 NOT FOUND:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/3862051/234465833-5f0214c4-ad9d-48cc-b34a-82388aea7a38.png">

**Comment by loicknuchel** [comment]
Thanks, seems GitHub is slowly removing classic projects...
Will rebuild it and change the link ;)

**Comment by loicknuchel** [comment]
Fixed!
Thanks
