### ISSUE TITLE
Virtual relations (manually created)

### ISSUE THREAD

**Issue by loicknuchel** [azimuttapp/azimutt#21]
Today Azimutt uses foreign keys as relations between columns (and so tables).
This is great but they are not the only way to do joins.
Some possible joins are either not declared (cf wordpress schema) or could not be declared, for performance reasons or flexibility (ex: polymorphic relations in Rails).

**Virtual relations** are relations present in the database but not declared as foreign keys in the schema.

With virtual relations, a user should be able to create new relations in his/her schema:

- click on "create virtual relation"
- click on the column referencing an other one
- click on the referenced column (both tables should be visible)

With this, columns could have multiple outgoing relations (ex: Rails polymorphic relations).

If you like this idea and want to see it in Azimutt, please leave a :+1: reaction to this issue.
Also don't hesitate to as questions or suggest different implementations on this.

**Comment by loicknuchel** [comment]
Implemented in https://github.com/azimuttapp/azimutt/pull/40

**Comment by michi-zuri** [comment]
It would be nice if virtual relations were visually more distinguishable from foreign key constraints. Right now, when I create a virtual relation I'm not sure how I'd know that it's markup and not a fk relation if I didn't add the relation myself.

**Comment by loicknuchel** [comment]
Yeah, I see what you mean.
For Azimutt, virtual relation are normal relations but in an other source. So they are not that different but indeed I could identify them. The bigger question for me is how to make them distinguishable? Color is already used for source table and dashed ones are for nullable foreign key. Maybe a dotted one? What do you think? Not sure if it would be clear.

**Comment by michi-zuri** [comment]
Yeah, it's not that easy I guess, because they may also be nullable or not. A special stroke-dasharray like 35,10,5,10,5,10,5,10 for nullable and 35,10 for required virtual relation might work?
