### ISSUE TITLE
Support oracle database import

### ISSUE THREAD

**Issue by orfeuml** [azimuttapp/azimutt#217]
[modelos.txt](https://github.com/azimuttapp/azimutt/files/11490336/modelos.txt)

**Comment by loicknuchel** [comment]
Hi @orfeuml 
I'm working on more connectors right now.
I made MySQL and I'm working on SQL Server. Oracle is next ;)

**Comment by adonai36** [comment]
Any news on when Oracle will be implemented?

**Comment by loicknuchel** [comment]
Hi @adonai36 
Thanks for reaching out on this.
We prioritize work based on customer need & size.
For now we focus more on database analysis and some AI features, but if you need it we can meet and discuss about it.
Or if you know Oracle database, you can also contribute, the hardest part of a connector is making the queries to extract the schema. [PostgreSQL](https://github.com/azimuttapp/azimutt/blob/main/libs/connector-postgres/src/postgres.ts#L189) is a good example ;)

**Comment by loicknuchel** [comment]
Should be available next week: https://github.com/azimuttapp/azimutt/pull/317 :smile:

**Comment by loicknuchel** [comment]
@orfeuml @adonai36 Oracle connector is now available :tada:
