### ISSUE TITLE
Better table layout algorithm

### ISSUE THREAD

**Issue by loicknuchel** [azimuttapp/azimutt#22]
Having a nice diagram is not possible without a good positioning.

Currently, Azimutt has the simplest possible layout algorithm: random position.
So it's up to the user to make a clear schema.

Of course Azimutt could do better here, several options:

## 1. Place tables on a grid

Instead of choosing a random position, place tables on a grid (with 50x50 squares for example) and try ti fit a table where it does not intersect with others, preferably on the current viewport but otherwise extend it (unzoom) to fit it.

## 2. Use a graph layout algorithm

[Dagre](https://github.com/dagrejs/dagre) is the layout lib used by [mermaid](https://mermaid-js.github.io/mermaid) and it's quite good and could also be used in Azimutt.

## 3. Use force layout algorithm

[Force layouts](https://package.elm-lang.org/packages/gampleman/elm-visualization/latest/Force) allows to group tables with many relations together. I already tried a PR (https://github.com/azimuttapp/azimutt/pull/37) but without much success so far.

## Others

- https://www.cs.ru.nl/bachelors-theses/2018/Bart_van_de_Put___4400496___Scoring_Entity-Relationship_Diagrams_Drawn_by_a_Computer_Algorithm.pdf
- https://www.yworks.com/pages/drawing-orthogonal-diagrams

## Azimutt implementations

Each implementation has its own merits and every one could be implemented so the user can select the one that fit better for his/her schema. They also can be used to position a newly show table or to recompute every table position on the existing schema.

Do you think this feature is important ? (leave a :+1: reaction if so)
If you have some experience is graph positioning, especially for Entity-Relationship diagram, I would love your input on this :smile:

**Comment by loicknuchel** [comment]
Work is started in https://github.com/azimuttapp/azimutt/pull/37 but still a lot to do...
Any help or advice is more than welcome ;)

Opened questions:
- which algorithm to use (I started experimenting with force layout)
- which libs can help (Elm or JS)
- what do you expect from this (will help define feature shape)

**Comment by stacy-rendall** [comment]
I think Grid would be a valuable addition to Azimutt, and comparatively simple to implement (compared to the proposed layout algorithms). The layout algorithms would be nice to have in the distant future, but a toggle-able grid would help users get 95% of what they need easily.
