### ISSUE TITLE
Import Prisma Schema

### ISSUE THREAD

**Issue by matbgn** [azimuttapp/azimutt#223]
Is there any way to import and visualize Prisma Schemas?

https://www.prisma.io/docs/concepts/components/prisma-schema

**Comment by loicknuchel** [comment]
Hi @matbgn 

No there isn't at this time.
But it's super fun I was asking this question on twitter a few days ago: https://twitter.com/loicknuchel/status/1665679239801106432 ^^

This would be nice indeed.
Doing some quick googling, seems this is a discussed topic with no official solution (https://github.com/prisma/prisma/issues/515) but at least one community one (https://github.com/loancrate/prisma-schema-parser).
I guess making some code to use this parser and format the object as expected from Azimutt won't be too difficult.
I'm focused on other topics right now (database connectors & data exploration) but I think I could make it by the end of the year.

**Comment by matbgn** [comment]
Nice!

I would be glad to sponsor (with a big coffee) this feature once it's deployed, let me know ;-)

Have a nice day

**Comment by loicknuchel** [comment]
Cool, would you join our Slack so we can discuss about your needs? (https://azimutt.app/slack)
I would be interested in the workflow you have and how to integrate it in the best way.

**Comment by matbgn** [comment]
@loicknuchel I responded in channel #ideas https://azimutt.slack.com/archives/C04S0N107MF/p1686553277713149

Best,

**Comment by loicknuchel** [comment]
PR started: https://github.com/azimuttapp/azimutt/pull/231

**Comment by loicknuchel** [comment]
Merged & Deployed :tada: 
Can you try it and tell me if everything is fine?

**Comment by matbgn** [comment]
Soooo coool!!!

Responded here https://azimutt.slack.com/archives/C04S0N107MF/p1689405256482089?thread_ts=1686553277.713149&cid=C04S0N107MF

Many thanks!

Would it be possible to do the same to update schema afterwards? Instead of using AML syntax/file. Are the building blocks ready for that?

**Comment by loicknuchel** [comment]
You mean updating your Prisma schema inside Azimutt instead of writing AML?
I have this in mind for a big improvement in sources: making them editable.
But unless I have contributors working on this, it will probably not be in 2023, I have a lot of more important features to deliver ^^

**Comment by matbgn** [comment]
Course I understand ;-)
