### ISSUE TITLE
using float type for price in the hero image

### ISSUE THREAD

**Issue by Mhdi-kr** [azimuttapp/azimutt#249]
Hello, I noticed something wrong in the hero image and I wanted to tell you about it. 

You've used float type for storing prices in the database which can get you in trouble because floats and doubles cannot accurately represent the base 10 multiples that we use for money.

[IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point)
[more info](https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency)

**Comment by loicknuchel** [comment]
Hi @Mhdi-kr 
Thanks for reporting, I see what you mean about float/double but not sure where you saw them on Azimutt for price.
Could you point me precisely where you saw it?
Thanks

**Comment by Mhdi-kr** [comment]
Sure!
https://azimutt.app/images/screenshots/azimutt-79bb1b71198a84a889aea7d55ec8cfa1.png?vsn=d

**Comment by loicknuchel** [comment]
Ah I see!
It's not on Azimutt but on Gospeak database ^^
Indeed not best ^^
