### ISSUE TITLE
Enum definition

### ISSUE THREAD

**Issue by sam-levy** [azimuttapp/azimutt#255]
It would be amazing to be able to define enums outside the tables and then just reference them in the table columns.
Something like:

```aml
enum state(active, disabled)

users
  id uuid pk
  state state

bank_accounts
  id uuid pk
  state state
  user_id uuid fk users.id
```

**Comment by loicknuchel** [comment]
Hi @sam-levy 

Great idea, I added it to my AML improvement checklist: https://github.com/azimuttapp/azimutt/issues/267, you can follow progress there.
