### ISSUE TITLE
Improve AML syntax

### ISSUE THREAD

**Issue by loicknuchel** [azimuttapp/azimutt#267]
[AML](https://github.com/azimuttapp/azimutt/blob/main/docs/aml/README.md) is a markup language to easily define database schema. It's made to be quick, easy and flexible to write to capture user intent rather than capture all the details needed for each database.
It already quite great but needs some improvement to handle additional features and use cases.
It would be nice also to add some developer utils to easy it's adoption.

Syntax improvements:

- [ ] handle nested columns (same as columns but with more indentation levels)
- [ ] handle composite relations
- [ ] define types/enum as standalone (cf https://github.com/azimuttapp/azimutt/issues/255)
- [ ] define a global schema for the whole AML file

Developer tools:

- [ ] Make a [JS library](https://github.com/azimuttapp/azimutt/tree/main/libs/parser-aml) to validate/parse/generate AML
- [ ] Make a syntax highlighter for a JS editor

**Comment by nameer** [comment]
#179 and #166 may be related to this issue.

**Comment by loicknuchel** [comment]
Thanks for your comment, why do you think they can be related?
They are more linked to UI display than AML as I'm Azimutt is focused on physical layer or db design, not on logical one.

**Comment by nameer** [comment]
My suggestion was based on the notion that representing relationships among tables in Azimutt may involve syntax changes in AML. While I acknowledge the primary focus on the physical layer, there might be a connection in terms of how AML syntax could be extended or modified to facilitate the representation of relationships in the UI.

**Comment by loicknuchel** [comment]
Thanks for your clarification.
For this I'm considering more inferences from the UI than changing the schema model.
For example:
- a relation from a column with a unique could be shown as a 1-1 relation
- a table with a primary key containing two relations could be shown as a n-n relation

If you see how AML could be improved for this, would be happy to discuss suggestions ;)
