### ISSUE TITLE
The link in share/embed does not work

### ISSUE THREAD

**Issue by nameer** [azimuttapp/azimutt#270]
When sharing a project, the link inside the iframe embed code doesn't work if I'm not signed in.

I haven't verified my email yet, so I'm wondering if that could be the reason (I've attempted to verify and am still awaiting the confirmation email 😅 ).

Additionally, it would be great if we could have a field with a direct link to the Azimutt schema page in the "share" page. Currently, I find myself copying the browser link or the link from the embed code.

**Comment by loicknuchel** [comment]
Hi @nameer 

To embed Azimutt you need to get the specific URL in the share modal (from the iframe tag).
To make it accessible without login, you have to create a private link inside the share modal as well.

Does it solves your issues?

**Comment by nameer** [comment]
> Hi @nameer
> 
> To embed Azimutt you need to get the specific URL in the share modal (from the iframe tag). To make it accessible without login, you have to create a private link inside the share modal as well.
> 
> Does it solves your issues?

Yes, I wasn't aware of the "Private Link" feature.
