### ISSUE TITLE
All dbs from Mongo service are accessed

### ISSUE THREAD

**Issue by LuisHPorras** [azimuttapp/azimutt#319]
## Description
I'm using Azimut v0.1.22 to explore a Mongo DB running in a docker container using ```npx azimutt explore mongodb://[user]:[password]@[host]:[port]/[db-name]```. The command works fine and launches the web application. The problem is, although I've used a specific db name to connect to, all my dbs in the mongo service are explored and as a side effect I can't read tables with the same name (the users table).

## Expected behaviour
When connecting to a specific db only explore that db's tables.

**Comment by loicknuchel** [comment]
Hi @LuisHPorras 
Made an update, it should be fine now if you specify you database in your url.
Let me know.
Cheers!

**Comment by LuisHPorras** [comment]
Yes! Works like a charm now, thanks a lot!
