### ISSUE TITLE
Different UI for tables and views

### ISSUE THREAD

**Issue by ad-si** [azimuttapp/azimutt#47]
They are 2 quite different things under the hood, so I guess they also should look different.

**Comment by loicknuchel** [comment]
You are right!
I have thought of this quite a lot but weren't able to come up with a good design to express this difference.
Maybe a different color in the header, an icon in front of the name or having it in italic or with a dashed underline...
Do you have any idea/preference ?

**Comment by ad-si** [comment]
All of them! 😛
I think the design should be quite different, so that there is absolutely no chance to accidentally misinterpret a view as a table and vice versa

I think i'd go with something like:

- Different background color (gray?)
- Icon left of the header text
- Italic font in header
- Different pattern for the header color (striped?)

**Comment by loicknuchel** [comment]
Haha, interesting. Didn't though of having so different UI, I will have to do some tests to see how it feels ^^
Maybe add also a little bit of transparency for views...

An other thing, I plan to add a project setting to enable or not the views, so you will be able to hide them if they are not relevant at some time.

**Comment by loicknuchel** [comment]
Hi @ad-si 
I changed the design to identify views with some italic and underline in view name header. I hope it will be clear enough.
I also added some options to hide views if you don't need them.
