### ISSUE TITLE
Search result dropdown list does not go away when clicking on canvas

### ISSUE THREAD

**Issue by kiendang** [azimuttapp/azimutt#50]
As title says, the search result dropdown list does not go away when clicking on the main canvas, only when clicking on the menu bar.

Cool app btw!

**Comment by kiendang** [comment]
Great! Looking forward to the UI revamp.

**Comment by loicknuchel** [comment]
Hi @kiendang 
The UI revamp is finally done!
Took me quite some time but it's released now, and the search problem is fixed.
So I'm closing this issue, feel free to open others if you see other problems or have feature ideas ;)
