### ISSUE TITLE
Table dropdown menu position changes when zooming out

### ISSUE THREAD

**Issue by zachdoctolib** [azimuttapp/azimutt#54]
Tested on Google Chrome Version 94.0.4606.81

https://user-images.githubusercontent.com/85943952/138722553-5f6c5fc8-2dcb-4015-afc0-fcca5842bd30.mov

**Comment by loicknuchel** [comment]
Hi @zachdoctolib 
I finally released my big bang refactoring and it's fixed now ;)
So closing the issue.
Feel free to open more if you see other bad things.
