### ISSUE TITLE
CSS issues when running locally via `elm-spa server`

### ISSUE THREAD

**Issue by nicokosi** [azimuttapp/azimutt#87]
Hello 👋,

I am curious about this project. I am trying to launch it on my machine in order to explore some databases. Badly, CSS issues visibly occur after launching `elm-spa server`:
<img width="1440" alt="Screenshot 2022-04-13 at 06 21 48" src="https://user-images.githubusercontent.com/3862051/163099863-90bca265-df4b-46b6-8134-1af3ef5122da.png">

For information:
* [installation/start logs](https://github.com/azimuttapp/azimutt/files/8478161/install-and-start.log).
* my current commit is 55246b2599ef5e0eaf34579135156ae45627faf7. 

Maybe that the [problem exists between chair and keyboard](https://en.wiktionary.org/wiki/PEBCAK) 😇. Thanks in advance for your help.

**Comment by loicknuchel** [comment]
Hi @nicokosi 

I think you didn't run the tailwind command: `npx tailwindcss -i ./public/styles.css -o ./public/dist/styles.css` (it's listed in dev commands but it's not clear at all, I should improve the readme ^^)

Tell me if this fix the problem.

**Comment by nicokosi** [comment]
Thank you @loicknuchel!
I tried on another machine and I got this error:
```
npx tailwindcss -i ./public/styles.css -o ./public/dist/styles.css                                                                                                     
(node:111785) UnhandledPromiseRejectionWarning: TypeError: fileContent.replaceAll is not a function
    at expandDynamicColors (/home/nkosinski/perso/azimutt/tailwind.config.js:6:24)
    at elm (/home/nkosinski/perso/azimutt/tailwind.config.js:27:49)
    at /home/nkosinski/perso/azimutt/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:46:32
    at /home/nkosinski/perso/azimutt/node_modules/tailwindcss/lib/processTailwindFeatures.js:43:53
    at Object.Once (/home/nkosinski/perso/azimutt/node_modules/tailwindcss/lib/cli.js:489:23)
    at LazyResult.runOnRoot (/home/nkosinski/perso/azimutt/node_modules/tailwindcss/peers/index.js:5131:27)
    at LazyResult.runAsync (/home/nkosinski/perso/azimutt/node_modules/tailwindcss/peers/index.js:5173:30)
    at LazyResult.async (/home/nkosinski/perso/azimutt/node_modules/tailwindcss/peers/index.js:5024:34)
    at LazyResult.then (/home/nkosinski/perso/azimutt/node_modules/tailwindcss/peers/index.js:5010:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:111785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:111785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Anyway, I think I will try on https://azimutt.app/ in the next days. I'll keep you updated.

**Comment by loicknuchel** [comment]
Ah shit! I will have to fix this.

**Comment by loicknuchel** [comment]
I used `replace` instead of `replaceAll` so it should be fine now ;)
Could you try it and tell me?

**Comment by loicknuchel** [comment]
Thanks to you, the README is now better :tada:
